{% set version = "1.4.0" %}
{% set name = "pygments_anyscript" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef6989e5ec85350e36442da0cbadec07c41ea3d2e0d301bf2086e72deb6caaed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.4
  run:
    - python >={{ python_min }}
    - pygments

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygments_anyscript

about:
  home: http://github.com/AnyBody/pygments-anyscript
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pygments lexer and style for the AnyScript language'

  description: |
    pygments_anyscript adds a plugin for Pygments to with a lexer and a style 
    for the AnyScript language. AnyScript is the scripting langugage used for 
    the AnyBody Modeling System; a system for multibody musculoskeletal 
    analysis.

  doc_url: https://github.com/AnyBody/pygments-anyscript
  dev_url: https://github.com/AnyBody/pygments-anyscript

extra:
  recipe-maintainers:
    - melund
